version: '3.6'

networks:
    project_network:
        driver: bridge
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www/boszhan
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
#      - ./_docker/certbot/conf:/etc/letsencrypt
#      - ./_docker/certbot/www:/var/www/certbot
    ports:
        - "80:80"
#        - "443:443"
    depends_on:
      - app
    container_name: project_nginx
    networks:
        - project_network

#  cerbot:
#      image: certbot/certbot
#      volumes:
#        - ./_docker/certbot/conf:/etc/letsencrypt
#        - ./_docker/certbot/www:/var/www/certbot
  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www/boszhan
      - /home/dev/index:/home/dev/index
    depends_on:
      - mysql
      - redis
    container_name: project_app
    networks:
        - project_network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: project
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    command:
      - --table_definition_cache=100
      - --performance_schema=0
      - --default-authentication-plugin=mysql_native_password
      - --innodb_use_native_aio=0
    volumes:
#      - ./init:/docker-entrypoint-initdb.d
      - ./tmp/mysql:/var/lib/mysql
    container_name: project_mysql
    networks:
        - project_network

  redis:
      image: redis:7.0
      container_name: project_redis
      volumes:
          - ./tmp/redis:/data
      ports:
          - "6379:6379"
      networks:
          - project_network


