version: '3'
networks:
    laravel:
        driver: bridge
services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - .:/var/www/html
            - ./docker/certbot/conf:/etc/letsencrypt
            - ./docker/certbot/www:/var/www/certbot
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
        depends_on:
            - app
        networks:
            - laravel
    certbot:
        image: certbot/certbot
        restart: unless-stopped
        volumes:
            - ./docker/certbot/conf:/etc/letsencrypt
            - ./docker/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        environment:
            - DB_HOST=db
            - DB_DATABASE=laravel
            - DB_USERNAME=user
            - DB_PASSWORD=secret
            - REDIS_HOST=redis
            - QUEUE_CONNECTION=redis
        command: [ "php", "/var/www/html/artisan", "serve", "--host=0.0.0.0", "--port=8000" ]
        networks:
            - laravel

